CREATE TABLE CLIENTE (
  IDCLIENTE SERIAL PRIMARY KEY,
  NOME VARCHAR(100),
  EMAIL VARCHAR(100),
  ENDERECO VARCHAR(200),
  TELEFONE VARCHAR(20),
  NUMERO INTEGER,
  BAIRRO VARCHAR(50),
  COMPLEMENTO VARCHAR(50),
  MUNICIPIO VARCHAR(50),
  CEP INTEGER,
  UF VARCHAR(2)
);

CREATE TABLE CATEGORIA (
  IDCATEGORIA SERIAL PRIMARY KEY,
  NOME VARCHAR(100),
  DESCRICAO TEXT
);

CREATE TABLE PRODUTO (
  IDPRODUTO SERIAL PRIMARY KEY,
  NOME VARCHAR(100),
  DESCRICAO TEXT,
  PRECO DECIMAL(10, 2),
  IDCATEGORIA INT REFERENCES CATEGORIA(IDCATEGORIA)
);

CREATE TABLE PEDIDO (
  IDPEDIDO SERIAL PRIMARY KEY,
  IDCLIENTE INT REFERENCES CLIENTE(IDCLIENTE),
  DATA_PEDIDO DATE,
  TOTAL DECIMAL(10, 2),
  STATUS VARCHAR(20),
  FORMA_PAGAMENTO VARCHAR(50)
);

CREATE TABLE ITENS_PEDIDO (
  IDITENSPEDIDO SERIAL PRIMARY KEY,
  IDPEDIDO INT REFERENCES PEDIDO(IDPEDIDO),
  IDPRODUTO INT REFERENCES PRODUTO(IDPRODUTO),
  QUANTIDADE INT,
  PRECO_UNITARIO DECIMAL(10, 2),
  DESCONTO DECIMAL(10, 2),
  SUBTOTAL DECIMAL(10, 2),
  OBSERVACAO TEXT
);

CREATE TABLE FORNECEDOR (
  IDFORNECEDOR SERIAL PRIMARY KEY,
  NOME VARCHAR(100),
  CNPJ VARCHAR(14),
  TELEFONE VARCHAR(20),
  EMAIL VARCHAR(100),
  ENDERECO VARCHAR(200)
);

CREATE TABLE ESTOQUE (
  IDESTOQUE SERIAL PRIMARY KEY,
  IDPRODUTO INT REFERENCES PRODUTO(IDPRODUTO),
  IDFORNECEDOR INT REFERENCES FORNECEDOR(IDFORNECEDOR),
  QUANTIDADE INT,
  DATA_ENTRADA DATE
);


