CREATE TABLE CLIENTE (
  IDCLIENTE SERIAL PRIMARY KEY,
  NOME VARCHAR(100),
  EMAIL VARCHAR(100),
  ENDERECO VARCHAR(200),
  TELEFONE VARCHAR(20)
);

CREATE TABLE CATEGORIA (
  IDCATEGORIA SERIAL PRIMARY KEY,
  NOME VARCHAR(100),
  DESCRICAO TEXT
);

CREATE TABLE PRODUTO (
  IDPRODUTO SERIAL PRIMARY KEY,
  NOME VARCHAR(100),
  DESCRICAO TEXT,
  PRECO DECIMAL(10, 2),
  IDCATEGORIA INT REFERENCES CATEGORIA(IDCATEGORIA)
);

CREATE TABLE PEDIDO (
  IDPEDIDO SERIAL PRIMARY KEY,
  IDCLIENTE INT REFERENCES CLIENTE(IDCLIENTE),
  DATA_PEDIDO DATE,
  TOTAL DECIMAL(10, 2)
);

CREATE TABLE ITENS_PEDIDO (
  IDITENSPEDIDO SERIAL PRIMARY KEY,
  IDPEDIDO INT REFERENCES PEDIDO(IDPEDIDO),
  IDPRODUTO INT REFERENCES PRODUTO(IDPRODUTO),
  QUANTIDADE INT,
  PRECO_UNITARIO DECIMAL(10, 2)
);